add logptr context assert and log_clone

diff --git a/test/helper.sh.in b/test/helper.sh.in
--- a/test/helper.sh.in
+++ b/test/helper.sh.in
@@ -106,3 +106,16 @@ function push_file() {
 		echo "2018-05-12 12:55:22 TRACE	[thread5]	clazz	callType: b: c: C, " >> $IN
 	done
 }
+
+function assert_file_contains {
+	COUNT=$(cat $2 | grep "$1" | wc -l)
+
+	if [ "$COUNT" != "1" ]; then
+		echo "expected to find '$1' in file but not found: $COUNT" 
+		if [ -f "$ERR" ]; then
+			cat $ERR
+		fi
+		cat $2
+		exit 1;
+	fi
+}
